### ISSUE TITLE
hyperkit returns 1 on clean exit/powerdown

### ISSUE THREAD

**Issue by rneugeba** [docker/hyperkit#108]
Running `hyperkitrun.sh` and use `sudo poweroff` cause the hyperkit process to exit with code 1. It would be nice if it exits with 0 on a clean guest shutdown

**Comment by rneugeba** [comment]
Looks like the exit code comes from `hyperkit.c:vmexit_suspend()`:
```
...
        switch ((int) (how)) {
        case VM_SUSPEND_RESET:
                exit(0);
        case VM_SUSPEND_POWEROFF:
                exit(1);
        case VM_SUSPEND_HALT:
                exit(2);
        case VM_SUSPEND_TRIPLEFAULT:
                exit(3);
        default:
                fprintf(stderr, "vmexit_suspend: invalid reason %d\n", how);
                exit(100);
        }
```

While this is also the case in `bhyve` using 1 as the exit code on poweroff makes it impossible to distinguish a clean poweroff from an error, which also returns 1 in several other functions.

I'm inclined to exit with 0 on poweroff (same as on `VM_SUSPEND_RESET`) as they are pretty similar and both seem to indicate a clean exit. Alternatively we could pick a different exit code for `VM_SUSPEND_POWEROFF`.

@ijc25 do you have a strong opinion either way?

**Comment by ijc25** [comment]
Given we appear to have defined `100` as explicit `invalid reason` perhaps we should use `101..N` as well defined reasons, which keeps us out of the way of other random `exit(N)` in the code which are typically using small `N`?

Otherwise, perhaps `POWEROFF` and `HALT` should `exit(0)` (I'm not sure what the distinction is, but they are both graceful shutdown and go away scenarios). I'm not sure about `RESET` also using `exit(0)` since the distinction between `POWEROFF`/`HALT` and `RESET` is something the caller is likely interested in since for `RESET` they might want to respawn `hyperkit` whereas the other two they may not (I'm talking most likely default reaction here). Some caller might actually prefer hyperkit to respawn itself, but not all will want that (maybe they want to adjust the h/w on first reboot -- i.e. to remove the installation ISO image) so punting the decision to the caller seems fine.

@rneugeba seems I have opinions, but not in any particular direction, sorry.
