### ISSUE TITLE
No network interface created on Host that links to Guest

### ISSUE THREAD

**Issue by AlmirKadric** [docker/hyperkit#45]
Currently there is no virtual network interface created on the `Host` (MacOSX) which links to the interface inside the `Guest` (VM). This creates a lot of limitation in terms of IP routing.

As it stands the `Guest` can route outwards and even ping the `Host` but the other way is not true. This also adds additional limitations to docker which are not desirable.

What I am trying to achieve is to create a route in the `Host` which hops over the `Guest` into one of its containers. However since there is no IP mapped to the `Guest` inside the `Host` there is no way to do this.

VirtualBox solves this by create a virtual interface with an IP address as such:
```
vboxnet5: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	ether 0a:00:27:00:00:05
	inet 172.16.41.1 netmask 0xffffff00 broadcast 172.16.41.255
```

Also in the past this was solved with docker-machine using the following:
```
sudo route -n add 172.17.0.0/16 $(docker-machine ip <MACHINE NAME>)
```

Furthermore, from what I have seen so far it seems that bhyve and xhyve do support creating tap interfaces on the `Host` which should map to the `Guest` which would solve this whole issue.
https://www.freebsd.org/doc/handbook/virtualization-host-bhyve.html
https://github.com/mist64/xhyve#networking
http://tuntaposx.sourceforge.net/

**Comment by AlmirKadric** [comment]
Edit: Seems this would be possible if an option is added to the docker configuration to allow the setting of the tap interface.

https://forums.docker.com/t/support-tap-interface-for-direct-container-access-incl-multi-host/17835/3

**Comment by rneugeba** [comment]
HyperKit allows you to create network interface (see `hyperkit.1`). For example:
```
sudo ./build/com.docker.hyperkit -A -m 512M -s 0:0,hostbridge c -s 2:0,virtio-net -l com1,stdio -f kexec,vmlinuz64,initrd.img,test/initrd.gz,earlyprintk=serial console=ttyS
```
will create a bridge interface on the host and a virtio network interface inside the VM. If `dhcp` is configured inside the VM it will get an IP address in the same range as the host bridge. For example in my case:
```
eth0      Link encap:Ethernet  HWaddr 1E:9D:A1:45:CF:32
          inet addr:192.168.64.24  Bcast:0.0.0.0  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:15 errors:0 dropped:0 overruns:0 frame:0
          TX packets:15 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1896 (1.8 KiB)  TX bytes:1760 (1.7 KiB)
```
and I can that IP address from the host.

**Comment by ijc25** [comment]
I don't think this is a hyperkit issue since as @rneugeba says hyperkit already supports this sort of thing.

I think this is actually a Docker 4 Mac feature request and so should be made via the D4M feedback channels (please consult the docs for the right place to go). However, if I understand the request correctly, the answer is that this functionality is exposed via the usual `-p` option to `docker run` (and its compose and swarm equivalents) to publish the container ports on the host. If I've misunderstood the use case then please clarify when making the request to D4M.

**Comment by AlmirKadric** [comment]
Thanks for that, i found a entry inside the forums with exactly what im after
https://forums.docker.com/t/support-tap-interface-for-direct-container-access-incl-multi-host/17835

**Comment by inancgumus** [comment]
So, what's the solution, why this issue has been closed without a solution?

**Comment by AlmirKadric** [comment]
@inancgumus The issue was closed since it wasn't an issue in hyperkit. Hyperkit does support the network interfaces required. The issue is that docker for mac is using it wrong, thus the additional external links. To clarify though, docker for mac still hasn't to my knowledge fixed this. I've given up hope to be honest =_=

**Comment by rneugeba** [comment]
Docker for Mac is not "using it wrong". It is using VPNKit to provide network connectivity, which does not create a host interface (and does not require to be run as `root`) and provides additional functionality like better VPN support and exposing container ports to localhost etc.

@inancgumus there are two comments above explaining why this was closed: https://github.com/moby/hyperkit/issues/45#issuecomment-232578871 and https://github.com/moby/hyperkit/issues/45#issuecomment-232608557

**Comment by inancgumus** [comment]
@AlmirKadric @rneugeba Hmm, sad. Is someone here from Docker? I've read almost all of the solutions and the topics but no luck yet. Probably, I'm going to install an ubuntu inside os x through a virtual machine (_which vaporizes the Docker's direct benefits_). 

It's been years and I still see this problems. I wonder where Docker spends this money. It forces us to use non-osx OSes. Of course, these claims can easily be defendable by Docker team, however, it doesn't make our developers' life easier, "as promised".

:(

**Comment by rneugeba** [comment]
I work for Docker. As mentioned above, the OP was requesting a feature which is already is present, hence this issue was closed. What you seem to be looking for is a feature in Docker for Mac (which uses hyperkit) and should open an issue on https://github.com/docker/for-mac/issues

**Comment by inancgumus** [comment]
@rneugeba I don't need to, thx for the advice, because there are many issues already lingering with little hope, calling help from Docker team:

* https://github.com/docker/for-mac/issues/1031
* https://github.com/docker/for-mac/issues/155
* https://github.com/docker/for-mac/issues/68
* https://github.com/docker/for-mac/issues/57

**Comment by AlmirKadric** [comment]
@rneugeba sorry for saying it was being used wrong, cant help but be snarky about it considering the timeline. To clarify it, docker for mac isn't using it wrong, its just isn't consistent across different platforms. On docker for windows and docker for linux you can route over the host virtual machine to get access to the guest containers. However in docker for mac this isn't the case due to the tap interface not being created and no means are provided to allow you to create it easily (there are some hackish attempts out there to get some form of routing working, some are listed inside the thread I mentioned).

But yes I agree, this isn't a problem with hyperkit and the issue belongs in the docker for mac issue tracker.

@inancgumus yes it is quite sad, I have given up hope on docker for mac fixing the issue any time soon. They seem swamped with other work, and this features/bug just doesn't seem to be priority. From what I have seen (or perhaps a gut feeling), there seems to be some conflict as to whether or not Docker should allow routing into the guest containers. It seems that on windows and linux it is more a side effect of the tools used and on mac providing this consistency would be going against some design choice that was made along the way. I do hope this is resolved soon as it is a very much needed feature for so many people, but I wouldn't hold my breath. Probably better to find a work around in the mean time.

**Comment by djangofan** [comment]
Is it possible that using Docker with Virtualbox instead of hyperkit , would solve the issue?    I am just mentioning since nobody in this thread mentioned it.

**Comment by djs55** [comment]
For Docker feature requests, take a look at the roadmap repo: https://github.com/docker/roadmap/issues?q=is%3Aissue+is%3Aopen+network

**Comment by enzofrnt** [comment]
Hi,
Any possibility of fix ?

**Comment by gregnr** [comment]
If a tun (L3) interface works for your needs, you can use [docker-mac-net-connect](https://github.com/chipmk/docker-mac-net-connect) which creates a lightweight WireGuard tunnel under the hood between macOS and the Docker Linux VM (just a single Go binary on macOS side since WireGuard is built into the Linux kernel).

**Comment by enzofrnt** [comment]
> If a tun (L3) interface works for your needs, you can use [docker-mac-net-connect](https://github.com/chipmk/docker-mac-net-connect) which creates a lightweight WireGuard tunnel under the hood between macOS and the Docker Linux VM (just a single Go binary on macOS side since WireGuard is built into the Linux kernel). 

Wouldn’t that VPN be a bit slow?

**Comment by gregnr** [comment]
That's the first I've heard of it - have you tried it? VPNs will always have extra overhead, but in the case of WireGuard it's very small - I doubt it's anything you would notice.

The current state of Docker for mac requires a tunnel to accomplish L2/L3 networking (without hacks). WireGuard was chosen for that project because the protocol is built into the Linux kernel - closer to the metal / faster than other VPNs today. Also doesn't require a background process on the Linux VM since it is handled via the kernel module. Topology wise it's just a single hop going between macOS host and Linux VM (via [VPNKit](https://github.com/moby/vpnkit)).

If you're having performance issues please submit an issue, I would love to investigate.

**Comment by enzofrnt** [comment]
@gregnr Alright, I'll give it a try.
However, I have a few questions. When you mention "hack", what exactly are you referring to? Is it possible to establish a direct connection between the LinuxKit interface and the Mac interface?
Also, can I use IPvLAN over this WireGuard setup to expose IPs on my local network?

Thanks you.

**Comment by gregnr** [comment]
These are the hacks I was referring to:
https://forums.docker.com/t/support-tap-interface-for-direct-container-access-incl-multi-host/17835

HyperKit fully supports bridge interfaces, but Docker for mac doesn't expose it. So the method above manually starts HyperKit with the modified config.

`ipvlan` in L2 mode would not work, since WireGuard operates over L3 (meaning DHCP, mDNS, etc won't work). `ipvlan` L3 should work but hasn't been tested. What is your use case for `ipvlan`?

**Comment by enzofrnt** [comment]
@gregnr 
If my understanding is right.
With this hack, I'm able to bind the interface from macOS witch I can find here :
<img width="678" alt="image" src="https://github.com/moby/hyperkit/assets/63660254/40c1103e-c5c1-4966-bf83-853050214ff0">

To the interface that are present in LinuxKit here :
Also, as I understand this command, give me access to the Linux kernel of Docker :
`nc -U ~/Library/Containers/com.docker.docker/Data/debug-shell.sock`
<img width="429" alt="image" src="https://github.com/moby/hyperkit/assets/63660254/ee4294f7-7a83-4964-b74b-f9331dd3af8c">

Right ?


Some HomeKit container doesn't like to be used with same IP and port forwarding. So I prefer `ipvlan` and that also easier to as one IP by service for me.

**Comment by enzofrnt** [comment]
And, by taking a look at it :
https://forums.docker.com/t/support-tap-interface-for-direct-container-access-incl-multi-host/17835

I'm not sure, I will be able to do it my self…
