### ISSUE TITLE
Ability to route from host to container

### ISSUE THREAD

**Issue by foxx** [docker/hyperkit#55]
As mentioned [here][1]

> Unfortunately, due to limitations in OS X, we’re unable to route traffic to containers, and from containers back to the host.

Are there any plans to add support for this, or any other workarounds which don't involve using port forwarding? Furthermore, if routing does not work then how exactly does port forwarding get the packets to the container?

[1]: https://docs.docker.com/docker-for-mac/networking/

**Comment by ijc25** [comment]
Sorry, I missed this back when it was filed.

Since this isn't really a hyperkit issue I don't know the answer, really this is to do with the integration into docker for mac, so you would probably have more luck at https://github.com/docker/for-mac. In fact I think maybe this is essentially the same topic as is covered by https://github.com/docker/for-mac/issues/155.
