### ISSUE TITLE
Prevent system entering power saving modes while docker runs

### ISSUE THREAD

**Issue by ilg-ul** [docker/hyperkit#69]
I am running some very long build scripts (20-30 mins) and if I keep the GUI busy, everything is fine.

However, if I leave the computer inactive, the builds crash with various errors.

Starting the script with `caffeinate` helps, but occasionally I still experience some hangouts. Restarting the script usually continues correctly.

Suggestion:

- enhance the docker software with code to prevent macOS to enter power saving modes

(At first glance I thought that this feature should be addressed by the `docker` utility, but since it is specific to macOS, I guess it is more appropriate to be handled by the hyperkit, if possible).

**Comment by ijc25** [comment]
Thanks for the report/suggestion

> However, if I leave the computer inactive, the builds crash with various errors.

If something is crashing then that is a bug, irrespective of whether power saving kicking in seems to cause it or not. Please would you open a ticket against https://github.com/docker/for-mac using the "Diagnostic's & Feedback" item in the whale menu so that a diagnostics bundle will be uploaded (ideally do so shortly after reproducing the issue). Please try and give as much detail as you can, including a repro case and specifics of the failure mode (e.g. what specifically do you mean by "crash").

> (At first glance I thought that this feature should be addressed by the docker utility, but since it is specific to macOS, I guess it is more appropriate to be handled by the hyperkit, if possible).

Independently from the bug you are apparently seeing, which we should try and get to the bottom of, it's an interesting suggestion that preventing the system entering low power modes while containers are running/building might be something docker for mac users might want, but higher level things such as this ought to be provided as part of the integration into Docker for Mac not hyperkit (I expect it will involve UI options, container level policies etc, which should be done at a higher level).

Ian.

**Comment by ilg-ul** [comment]
the separate issue was recorded, see https://github.com/docker/for-mac/issues/828.
